### ISSUE TITLE
no_mangle attribute in production systems

### ISSUE THREAD

**Issue by afonsolage** [rksm/hot-lib-reloader-rs#10]
If I understood correctly, the `HotModule` will parse and expose as hot-reloadable all public no_mangle functions, but I was wondering if marking systems functions as `#[no_mangle]` may impact production performance, since AFAIK Rust compiler won't be able to fully otimize those functions.

It's possible somehow to only mark `#[no_mangle]` on hot-reload builds?

**Comment by rksm** [comment]
That is a very good point, thanks for bringing that up. I created [a `no-mangle-if-debug` helper crate](https://crates.io/crates/no-mangle-if-debug) to address this.
